# Generated by Django 3.1.2 on 2021-05-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
