# Generated by Django 3.1.2 on 2021-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210527_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='country_id',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturer_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='number_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
