# Generated by Django 3.1.2 on 2021-05-27 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210527_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='username',
            field=models.CharField(default=datetime.datetime(2021, 5, 27, 14, 13, 58, 768239, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
