# Generated by Django 3.1.2 on 2021-05-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='username',
        ),
    ]
