# Generated by Django 3.1.2 on 2021-05-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='Product_name',
        ),
    ]
